name: Clone Travel Map
description: A travel map that helps you find the best places to visit
full_description: 'It provides features like choosing the correct destination, making bookings, and organizing the trip. It provides solutions for every problem a traveller might face during their journey. It provide a comprehensive list of information about a destination: current weather, best places to hangout, and city current trends.<br>
<br>With a lot of features:
<br>- Destinations
<br>- Travel
<br>- My Trips
<br>- Utility'
android: https://jame-louis.github.io/clone-travel-map-landing-page/
screenshots:
  - all_cities.png
  - hotel_book.png
  - mytrip_info.png
  - checklist.png

